autoload -Uz is-at-least

export ENHANCD_COMMAND='cd'
zplug "b4b4r07/enhancd", use:init.sh

zplug "zsh-users/zsh-syntax-highlighting"
zplug "zsh-users/zsh-completions"
zplug "zsh-users/zsh-autosuggestions"

zplug "yasuhiroki/zshef", use:init.sh
zplug "yasuhiroki/tb", as:command, use:tb
zplug "yasuhiroki/bttf-color-zsh"

zplug 'molovo/revolver', as:command, use:revolver
zplug 'zunit-zsh/zunit', as:command, use:zunit, hook-build:'./build.zsh'
zplug 'marzocchi/zsh-notify'

if ! zplug check --verbose; then
    printf "Install? [y/N]: "
    if read -q; then
        echo; zplug install
    fi
fi

zplug load

source ~/.my-zshrc.zsh
