version: 2
jobs:
  build:
    machine:
      enabled: true
    steps:
      - checkout
      - run:
          command: |
            cd zshef
            docker build -t yasuhiroki/fudebako-base . |& tee log
            if cat log | fgrep '[ZSHEF][ERROR]'; then
              echo "ERROR in zshef run"
              return 1
            fi
