# Enable native Mac OS X copy/paste
set-option -g default-shell $SHELL
set-option -g default-command "reattach-to-user-namespace -l $SHELL"

bind-key -T copy-mode-vi v send -X begin-selection
bind-key -T copy-mode-vi y send -X copy-pipe-and-cancel "reattach-to-user-namespace pbcopy"
unbind   -T copy-mode-vi Enter
bind-key -T copy-mode-vi Enter send -X copy-pipe-and-cancel "reattach-to-user-namespace pbcopy"
