export ENHANCD_COMMAND='cd'
zplug "b4b4r07/enhancd", use:init.sh

zplug "zsh-users/zsh-syntax-highlighting", defer:2

zplug "zsh-users/zsh-completions"
zplug "zsh-users/zsh-autosuggestions"

setopt share_history
setopt hist_ignore_dups

zplug "yasuhiroki/bttf-color-zsh"

if ! zplug check --verbose; then
    printf "Install? [y/N]: "
    if read -q; then
        echo; zplug install
    fi
fi

zplug load

source ~/.my-zshrc.zsh
