FROM yasuhiroki/fudebako-base
MAINTAINER Yasuhiro Kiyota

RUN source /root/.nvm/nvm.sh \
    && nvm install 4.5 \
    && cd /root/github.com/yasuhiroki/iypymtiycaa \
    && bash ./install/install-npm-global.sh
